#!/bin/bash
curl 'http://localhost:8080/classes.iastate.edu/app/rest/courses/preferences' \
 -X POST \
 -H 'Content-Type: application/json; charset=UTF-8' \
 -H 'Origin: https://classes.iastate.edu' \
 --data-raw $'{"defSem":2,"selectedTerm":2,"selectedDepartment":"MATH"}'

#-H 'Accept-Encoding: gzip, deflate, br' \
